spring.application.name=soc-kev-agent
server.port=8080
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.cache.type=simple
logging.level.root=INFO
logging.level.com.deloitte.cyber=DEBUG
cisa.kev.url=https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
nvd.api.url=https://services.nvd.nist.gov/rest/json/cves/2.0
cache.kev.ttl-hours=24